name: dartcache
description: Comprehensive cross-platform Dart cache library for efficient in-memory data storage.
version: 1.0.0
repository: https://github.com/tomasweigenast/dartcache.git
issues: https://github.com/tomasweigenast/dartcache/issues

environment:
  sdk: ^3.4.0

dependencies:

dev_dependencies:
  lint: ^2.3.0
  test: ^1.24.0
